# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seventiny_cloud_faas_proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seventiny_cloud_faas_proto',
  package='SevenTiny.Cloud.FaaS',
  syntax='proto3',
  serialized_options=b'\252\002\031SevenTiny.Cloud.FaaS.GRpc',
  serialized_pb=b'\n\x1aseventiny_cloud_faas_proto\x12\x14SevenTiny.Cloud.FaaS\"\x07\n\x05\x45mpty\"\x86\x02\n\rDynamicScript\x12\x10\n\x08TenantId\x18\x01 \x01(\x05\x12\x0e\n\x06Script\x18\x02 \x01(\t\x12\x15\n\rClassFullName\x18\x03 \x01(\t\x12\x14\n\x0c\x46unctionName\x18\x04 \x01(\t\x12\x12\n\nParameters\x18\x05 \x01(\t\x12=\n\x08Language\x18\x06 \x01(\x0e\x32+.SevenTiny.Cloud.FaaS.DynamicScriptLanguage\x12\x1d\n\x15IsExecutionStatistics\x18\x07 \x01(\x08\x12\x17\n\x0fIsTrustedScript\x18\x08 \x01(\x08\x12\x1b\n\x13MillisecondsTimeout\x18\t \x01(\x05\"\x83\x01\n\x1a\x44ynamicScriptExecuteResult\x12\x11\n\tIsSuccess\x18\x01 \x01(\x08\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x03 \x01(\t\x12\x15\n\rProcessorTime\x18\x04 \x01(\x03\x12\x1c\n\x14TotalMemoryAllocated\x18\x05 \x01(\x03*0\n\x15\x44ynamicScriptLanguage\x12\x0b\n\x07Unknown\x10\x00\x12\n\n\x06\x43sharp\x10\x01\x32\xdf\x01\n\x15\x44ynamicScriptExecutor\x12\x64\n\x0b\x43heckScript\x12#.SevenTiny.Cloud.FaaS.DynamicScript\x1a\x30.SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult\x12`\n\x07\x45xecute\x12#.SevenTiny.Cloud.FaaS.DynamicScript\x1a\x30.SevenTiny.Cloud.FaaS.DynamicScriptExecuteResultB\x1c\xaa\x02\x19SevenTiny.Cloud.FaaS.GRpcb\x06proto3'
)

_DYNAMICSCRIPTLANGUAGE = _descriptor.EnumDescriptor(
  name='DynamicScriptLanguage',
  full_name='SevenTiny.Cloud.FaaS.DynamicScriptLanguage',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Csharp', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=460,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_DYNAMICSCRIPTLANGUAGE)

DynamicScriptLanguage = enum_type_wrapper.EnumTypeWrapper(_DYNAMICSCRIPTLANGUAGE)
Unknown = 0
Csharp = 1



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='SevenTiny.Cloud.FaaS.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=59,
)


_DYNAMICSCRIPT = _descriptor.Descriptor(
  name='DynamicScript',
  full_name='SevenTiny.Cloud.FaaS.DynamicScript',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TenantId', full_name='SevenTiny.Cloud.FaaS.DynamicScript.TenantId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Script', full_name='SevenTiny.Cloud.FaaS.DynamicScript.Script', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClassFullName', full_name='SevenTiny.Cloud.FaaS.DynamicScript.ClassFullName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FunctionName', full_name='SevenTiny.Cloud.FaaS.DynamicScript.FunctionName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Parameters', full_name='SevenTiny.Cloud.FaaS.DynamicScript.Parameters', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Language', full_name='SevenTiny.Cloud.FaaS.DynamicScript.Language', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsExecutionStatistics', full_name='SevenTiny.Cloud.FaaS.DynamicScript.IsExecutionStatistics', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsTrustedScript', full_name='SevenTiny.Cloud.FaaS.DynamicScript.IsTrustedScript', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MillisecondsTimeout', full_name='SevenTiny.Cloud.FaaS.DynamicScript.MillisecondsTimeout', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=324,
)


_DYNAMICSCRIPTEXECUTERESULT = _descriptor.Descriptor(
  name='DynamicScriptExecuteResult',
  full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IsSuccess', full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult.IsSuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult.Data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProcessorTime', full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult.ProcessorTime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TotalMemoryAllocated', full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult.TotalMemoryAllocated', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=458,
)

_DYNAMICSCRIPT.fields_by_name['Language'].enum_type = _DYNAMICSCRIPTLANGUAGE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['DynamicScript'] = _DYNAMICSCRIPT
DESCRIPTOR.message_types_by_name['DynamicScriptExecuteResult'] = _DYNAMICSCRIPTEXECUTERESULT
DESCRIPTOR.enum_types_by_name['DynamicScriptLanguage'] = _DYNAMICSCRIPTLANGUAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'seventiny_cloud_faas_proto_pb2'
  # @@protoc_insertion_point(class_scope:SevenTiny.Cloud.FaaS.Empty)
  })
_sym_db.RegisterMessage(Empty)

DynamicScript = _reflection.GeneratedProtocolMessageType('DynamicScript', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMICSCRIPT,
  '__module__' : 'seventiny_cloud_faas_proto_pb2'
  # @@protoc_insertion_point(class_scope:SevenTiny.Cloud.FaaS.DynamicScript)
  })
_sym_db.RegisterMessage(DynamicScript)

DynamicScriptExecuteResult = _reflection.GeneratedProtocolMessageType('DynamicScriptExecuteResult', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMICSCRIPTEXECUTERESULT,
  '__module__' : 'seventiny_cloud_faas_proto_pb2'
  # @@protoc_insertion_point(class_scope:SevenTiny.Cloud.FaaS.DynamicScriptExecuteResult)
  })
_sym_db.RegisterMessage(DynamicScriptExecuteResult)


DESCRIPTOR._options = None

_DYNAMICSCRIPTEXECUTOR = _descriptor.ServiceDescriptor(
  name='DynamicScriptExecutor',
  full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecutor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=511,
  serialized_end=734,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckScript',
    full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecutor.CheckScript',
    index=0,
    containing_service=None,
    input_type=_DYNAMICSCRIPT,
    output_type=_DYNAMICSCRIPTEXECUTERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='SevenTiny.Cloud.FaaS.DynamicScriptExecutor.Execute',
    index=1,
    containing_service=None,
    input_type=_DYNAMICSCRIPT,
    output_type=_DYNAMICSCRIPTEXECUTERESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DYNAMICSCRIPTEXECUTOR)

DESCRIPTOR.services_by_name['DynamicScriptExecutor'] = _DYNAMICSCRIPTEXECUTOR

# @@protoc_insertion_point(module_scope)
